name: default flow invoker

on:
  push:
    branches:
      - main
      - '[0-9].[0-9]'
  pull_request:
      branches:
      - main
      - '[0-9].[0-9]'

jobs:
  invoke_default_flow:
    if: (!endsWith(github.head_ref, 'docs') && !endsWith(github.head_ref, 'noci'))
    uses: ./.github/workflows/flows/default.yml
    secrets: inherit

  invoke_codeql_flow:
    if: (!endsWith(github.head_ref, 'docs') && !endsWith(github.head_ref, 'noci'))
    uses: ./.github/workflows/flows/codeql-analysis.yml
    secrets: inherit
